const UPDATE_CANVS_IMAGE = "UPDATE_CANVS_IMAGE";
const UPDATE_CANVS_TITLE = "UPDATE_CANVS_TITLE";
const UPDATE_BRIGHTNESS = "UPDATE_BRIGHTNESS";
const UPDATE_GREYSCALE = "UPDATE_GREYSCALE";
const UPDATE_SEPIA = "UPDATE_SEPIA";

export default {
	UPDATE_CANVS_IMAGE,
	UPDATE_CANVS_TITLE,
	UPDATE_BRIGHTNESS,
	UPDATE_GREYSCALE,
	UPDATE_SEPIA
}